# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9990cf778b689b096a64b6d2a0294b35be623daf17d6ec9a560171afaa17e9d5c5e3f97d3c72ab0a98c6ca94ffa96cd883a61b99a8fd00a65357f3fea6149d4c

test:
  secret_key_base: 41eef4bb22e15693b2338f41d69102785d0622062b6cb92344764a29d36bed0420768ea2eb0254a9a38446cd731159bd47fe1231c055d1638dca50ea625da05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
