#!/bin/sh

if [ -z "$1" ]; then
  echo 'Please specify your database'
  exit 1
fi

without='postgres mysql sqlite'
without=$(echo "${without}" | sed "s/$1//g")

export RAILS_ENV=production

bundle install --deployment --without development test $without

bundle exec rake casino_core:db:schema:load

cp config/database.yml.example.$1 config/database.yml
cp config/cas.yml.example config/cas.yml

bundle exec rake assets:precompile
