#!/bin/sh

if [ -z "$1" ]; then
  echo 'Please specify your database'
  exit 1
fi

without='postgres mysql'
without=$(echo "${without}" | sed "s/$1//g")

export RAILS_ENV=production

bundle install --deployment --without development test $without

cp -v config/database.yml.example.$1 config/database.yml
cp -v config/cas.yml.example config/cas.yml

echo 'Please configure your database in config/database.yml and hit ENTER when I should continue...'
read

bundle exec rake casino_core:db:schema:load
bundle exec rake assets:precompile
